config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get 'designs' => 'static_pages#designs'
  get 'testimonials' => 'static_pages#testimonials'
  get 'approach' => 'static_pages#approach'
  get 'contact' => 'static_pages#contact'
  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  mount Judge::Engine => '/judge'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "CM Suby Website Email Message",
      :to => "cmsuby@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if request.xhr?
      if @contact.deliver
        render plain: "OK: Email sent."
      else
        render plain: "Error: email not sent.", status: 422
      end
    else
      if @contact.deliver
        flash.now[:notice] = 'Thank you! Your message has been sent to cmsuby@gmail.com. We will respond promptly!'
        render :'static_pages/contact'
      else
        flash.now[:notice] = 'Something went wrong, this email form is not working. Please send an email to cmsuby@gmail.com directly. Thank you!'
        render :'static_pages/contact'
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
     @contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/_info.html.erb
  <li><a href="tel:+1-973-951-5570" class="button large">1-973-951-5570</a></li>
  <li><a href="mailto:cmsuby@gmail.com" class="button secondary large">cmsuby@gmail.com</a></li>

app/views/contacts/_new.html.erb
<div align="center">
  <h3>Email us:</h3>
  <%= form_for @contact, :builder => Judge::FormBuilder, url: '/contacts' do |f| %>
    <%= f.text_field :name, placeholder: 'Name', :validate => true %>
    <%= f.text_field :email, placeholder: 'Email', :validate => true %>
    <%= f.text_area :message, placeholder: 'Message', :validate => true %>
    <div>
      <br>
      <%= f.submit "send message", class: 'button' %>
    </div>
  <% end %>
</div>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/galleries/_banner.html.erb
<img src="/images/index_slides/banner_slide_1.png">
<img src="/images/index_slides/banner_slide_2.png">
<img src="/images/index_slides/banner_slide_3.png">
<img src="/images/index_slides/banner_slide_4.png">
<img src="/images/index_slides/banner_slide_5.png">
<img src="/images/index_slides/banner_slide_6.png">

app/views/galleries/_bathroom.html.erb
<div class="row">
<div class="large-12 columns">
<h3>Bathroom</h3>
<ul class="clearing-thumbs small-block-grid-1 medium-block-grid-2 large-block-grid-4" data-clearing>
<li>
<a href="/images/bathroom/berkeley/bathroom_01.jpg"><img data-caption="Berkeley Heights, NJ" src="/images/bathroom/berkeley/bathroom_01_thumbnail.png"></a>
</li>
<li>
<a href="/images/bathroom/berkeley/bathroom_02.jpg"><img data-caption="Berkeley Heights, NJ" src="/images/bathroom/berkeley/bathroom_02_thumbnail.png"></a>
</li>
<li>
<a href="/images/bathroom/berkeley/bathroom_03.jpg"><img data-caption="Berkeley Heights, NJ"src="/images/bathroom/berkeley/bathroom_03_thumbnail.png"></a>
</li>
<li>
<a href="/images/bathroom/berkeley/bathroom_04.jpg"><img data-caption="Berkeley Heights, NJ"src="/images/bathroom/berkeley/bathroom_04_thumbnail.png"></a>
</li>
<li>
<a href="/images/bathroom/morristown/bathroom_01.jpg"><img data-caption="Morristown, NJ" src="/images/bathroom/morristown/bathroom_01_thumbnail.png"></a>
</li>
<li>
<a href="/images/bathroom/morristown/bathroom_02.jpg"><img data-caption="Morristown, NJ" src="/images/bathroom/morristown/bathroom_02_thumbnail.png"></a>
</li>
<li>
<a href="/images/bathroom/neshanic/bathroom_01.jpg"><img data-caption="Neshanic Station, NJ" src="/images/bathroom/neshanic/bathroom_01_thumbnail.png"></a>
</li>
<li>
<a href="/images/bathroom/neshanic/bathroom_02.jpg"><img data-caption="Neshanic Station, NJ" src="/images/bathroom/neshanic/bathroom_02_thumbnail.png"></a>
</li>
<li>
<a href="/images/bathroom/neshanic/bathroom_03.jpg"><img data-caption="Neshanic Station, NJ" src="/images/bathroom/neshanic/bathroom_03_thumbnail.png"></a>
</li>
<li>
<a href="/images/bathroom/neshanic/bathroom_04.jpg"><img data-caption="Neshanic Station, NJ" src="/images/bathroom/neshanic/bathroom_04_thumbnail.png"></a>
</li>
<li>
<a href="/images/bathroom/neshanic/bathroom_05.jpg"><img data-caption="Neshanic Station, NJ" src="/images/bathroom/neshanic/bathroom_05_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/neshanic/bathroom_06.jpg"><img data-caption="Neshanic Station, NJ" src="/images/bathroom/neshanic/bathroom_06_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/neshanic/bathroom_07.jpg"><img data-caption="Neshanic Station, NJ" src="/images/bathroom/neshanic/bathroom_07_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/orange/bathroom_01.jpg"><img data-caption="Orange, NJ" src="/images/bathroom/orange/bathroom_01_thumbnail.png"></a>
</li>


<li>
<a href="/images/bathroom/springfield/bathroom_01.jpg"><img data-caption="Springfield, NJ" src="/images/bathroom/springfield/bathroom_01_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/warren/bathroom_01.jpg"><img data-caption="Warren, NJ" src="/images/bathroom/warren/bathroom_01_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/warren/bathroom_02.jpg"><img data-caption="Warren, NJ" src="/images/bathroom/warren/bathroom_02_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/warren/bathroom_03.jpg"><img data-caption="Warren, NJ" src="/images/bathroom/warren/bathroom_03_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/warren/bathroom_04.jpg"><img data-caption="Warren, NJ" src="/images/bathroom/warren/bathroom_04_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/warren/bathroom_05.jpg"><img data-caption="Warren, NJ" src="/images/bathroom/warren/bathroom_05_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/warren/bathroom_06.jpg"><img data-caption="Warren, NJ" src="/images/bathroom/warren/bathroom_06_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/warren/bathroom_07.jpg"><img data-caption="Warren, NJ" src="/images/bathroom/warren/bathroom_07_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/warren/bathroom_08.jpg"><img data-caption="Warren, NJ" src="/images/bathroom/warren/bathroom_08_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/watchung/powder_01.jpg"><img data-caption="Watchung, NJ" src="/images/bathroom/watchung/powder_01_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/westorange/bathroom_01.jpg"><img data-caption="West Orange, NJ" src="/images/bathroom/westorange/bathroom_01_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/westorange/bathroom_02.jpg"><img data-caption="West Orange, NJ" src="/images/bathroom/westorange/bathroom_02_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/westorange/bathroom_03.jpg"><img data-caption="West Orange, NJ" src="/images/bathroom/westorange/bathroom_03_thumbnail.png"></a>
</li>

<li>
<a href="/images/bathroom/westorange/bathroom_04.jpg"><img data-caption="West Orange, NJ" src="/images/bathroom/westorange/bathroom_04_thumbnail.png"></a>
</li>


</ul>
</div>
</div>

app/views/galleries/_kitchen.html.erb
<div class="row">
<div class="large-12 columns">
<h3>Kitchen</h3>
<ul class="clearing-thumbs small-block-grid-1 medium-block-grid-2 large-block-grid-4" data-clearing>

<li>
<a href="images/kitchen/orange/kitchen_01.jpg">
<img data-caption="Orange, NJ" src="images/kitchen/orange/kitchen_01_thumb.png"></a>
</li>

<li>
<a href="images/kitchen/morristown/kitchen_01.jpg">
<img data-caption="Morristown, NJ" src="images/kitchen/morristown/kitchen_01_thumb.png"></a>
</li>

<li>
<a href="images/kitchen/morristown/kitchen_02.jpg">
<img data-caption="Morristown, NJ" src="images/kitchen/morristown/kitchen_02_thumb.png"></a>
</li>

<li>
<a href="images/kitchen/watchung/kitchen_01.jpg">
<img data-caption="Watchung, NJ" src="images/kitchen/watchung/kitchen_01_thumb.png"></a>
</li>

<li>
<a href="images/kitchen/westorange/kitchen_01.jpg">
<img data-caption="West Orange, NJ" src="images/kitchen/westorange/kitchen_01_thumb.png"></a>
</li>

<li>
<a href="images/kitchen/westorange/kitchen_02.jpg">
<img data-caption="West Orange, NJ" src="images/kitchen/westorange/kitchen_02_thumb.png"></a>
</li>

<li>
<a href="images/kitchen/westorange/kitchen_03.jpg">
<img data-caption="West Orange, NJ" src="images/kitchen/westorange/kitchen_03_thumb.png"></a>
</li>


</ul>
</div>
</div>

app/views/galleries/_laundry.html.erb
<div class="row">
<div class="large-12 columns">
<h3>Laundry Room</h3>
<ul class="clearing-thumbs small-block-grid-1 medium-block-grid-2 large-block-grid-4" data-clearing>
<li>
<a href="images/laundry/springfield/laundry_01.jpg">
<img data-caption="Springfield, NJ" src="images/laundry/springfield/laundry_01_thumbnail.png"></a>
</li>
<li>
<a href="images/laundry/morristown/laundry_01.jpg">
<img data-caption="Morristown, NJ" src="images/laundry/morristown/laundry_01_thumbnail.png"></a>
</li>
</ul>
</div>
</div>

app/views/galleries/_new.html.erb
<div align="center">
  <%= simple_form_for @contact, :html => {:class => 'class-goes-here' } do |f| %>
    <%= f.input :name, :required => true, :placeholder =>"Name" %>
    <%= f.input :email, :required => true, :placeholder => "Email" %>
    <%= f.input :message, :as => :text, :required => true, :placeholder => "Your Message", :input_html => { :rows => 7 , :style => 'width: 100%'} %>
    <div>
      </br>
      <%= f.button :submit, 'send message', :class=> "class-goes-here" %>
    </div>
  <% end %>
</div>

app/views/galleries/_other.html.erb
<div class="row">
<div class="large-12 columns">
<h3>Other</h3>

<ul class="clearing-thumbs small-block-grid-1 medium-block-grid-2 large-block-grid-4" data-clearing>

<li>
<a href="images/other/foyer_01.jpg">
<img data-caption="Foyer - Watchung, NJ" src="images/other/foyer_01_thumbnail.png"></a>
</li>

<li>
<a href="images/other/hallway_01.jpg">
<img data-caption="Hallway - Watchung, NJ" src="images/other/hallway_01_thumbnail.png"></a>
</li>

<li>
<a href="images/other/living_01.jpg">
<img data-caption="Living Room - Orange, NJ" src="images/other/living_01_thumbnail.png"></a>
</li>
<li>
<a href="images/other/living_02.jpg">
<img data-caption="Living Room - Watchung, NJ" src="images/other/living_02_thumbnail.png"></a>
</li>


<li>
<a href="images/other/living_03.jpg">
<img data-caption="Living Room - Morristown, NJ" src="images/other/living_03_thumbnail.png"></a>
</li>

</ul>
</div>
</div>

app/views/layouts/_header.html.erb
    <!-- Navigation -->
    <div class="fixed">

 <nav class="top-bar" data-topbar role="navigation">
         <ul class="title-area">
          <li class="name">
            <h2><div class="logo show-for-small-only"><%=link_to image_tag("small_logo.png"), root_path%></h2>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">

          <div class="logo-wrapper hide-for-small-only">
            <div class="logo">
              <%=link_to image_tag("logo_test.png"), root_path%>
            </div>
          </div>

          <!-- Right Nav Section -->
          <ul class="right">
            <li><%=link_to "DESIGNS", designs_path%></li>
            <li><%=link_to "TESTIMONIALS", testimonials_path %></li>
          </ul>

          <!-- Left Nav Section -->
          <ul class="left">
          <li><%=link_to "APPROACH", approach_path%></li>
          <li><%=link_to "CONTACT", contact_path %></li>
          </ul>

        </section>
      </nav>

    </div><!-- /navigation -->

app/views/layouts/_nav.html.erb
    <header class="navbar navbar-inverse">
      <div class="navbar-class">
        <div class="container">
          <ul class="nav navbar-nav">
            <li><%=link_to "HOME", root_path%></li>
            <li><%=link_to "DESIGNS", designs_path%></li>
            <li><%=link_to "TESTIMONIALS", testimonials_path %></li>
            <li><%=link_to "CONTACT", contact_path %></li>
          </ul>
        </div>
       </div>
     </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "CM Suby" %></title>

<link href='https://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>

<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

<link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true  %>
    <%= csrf_meta_tags %>
  </head>

  <header>

    <%= render 'layouts/header' %>

  </header>


  <body>

    <%= yield %>

  </body>

<footer>
<div class="row">
<div class="large-12 columns">
<div class="row">
<div class="small-6 large-6 columns">
<p><img src="images/cmsuby_logo.jpg"></p>
</div>
<div class="small-6 large-6 columns">
<ul class="inline-list right">
<li>Northern NJ</li>
<li>1-973-951-5570</li>
<li>cmsuby@gmail.com</li>
<li>
<%= link_to "Contact", contact_path, class: "button secondary tiny" %>
</li>
</ul>
</div>
</div>

<p class="copyright">&copy; Copyright 2016 Jason Wang and Phil Sofia</p>
</div>
</div>


</footer>



</html>

app/views/static_pages/approach.html.erb
<div class="row">
  <div class="large-12 columns">
    <h2>Our Approach</h2>
    <p class="subheader"> At CM Suby, we understand that redesigning a home can be stressful to your daily routine. Your home is important to you and we take all the necessary precautions to ensure a successful project. Check below for a look into a typical bathroom renovation.</p>

    <div id='container1' div class="twentytwenty-container">
      <img alt="Sample before" src="/images/approach/bathroom_before.png"/>
      <img alt="Sample after" src="/images/approach/bathroom_after.png"/>
    </div>

    <hr class="style-two">
    <div class="row" data-equalizer>
      <div class="medium-4 large-4 columns">
        <ul class="pricing-table" data-equalizer-watch>
          <li class="title">Phase 1</li>
          <li class="price">Pre-work</li>
          <li class="bullet-item">Apply for all necessary permits</li>
          <li class="bullet-item">Protect the house</li>
          <li class="bullet-item">Gut and remove material off premises</li>
          <li class="bullet-item">Rebuild area according to blueprints/drawings.</li>
        </ul>
      </div>
      <div class="medium-4 large-4 columns">
        <ul class="pricing-table" data-equalizer-watch>
          <li class="title">Phase 2</li>
          <li class="price">Construction</li>
          <li class="bullet-item">Rough electrical or electrical upgrades, if necessary</li>
          <li class="bullet-item">Set up rough inspections for plumbing, building and electrical</li>
          <li class="bullet-item">Insulation upgrade/insulation inspection</li>
          <li class="bullet-item">Sheetrock/tape/spackle (3 coats)</li>
        </ul>
      </div>
      <div class="medium-4 large-4 columns">
        <ul class="pricing-table" data-equalizer-watch>
          <li class="title">Phase 3</li>
          <li class="price">Final Touches</li>
          <li class="bullet-item">Tile installation/grout</li>
          <li class="bullet-item">Trim work /trim out fixtures plumbing/electrical</li>
          <li class="bullet-item">Final measurements for shower or tub door</li>
          <li class="bullet-item">When completed final inspections scheduled (plumbing-building-electrical)</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <hr class="style-two">
    <h2>Quality</h2>
    <p class="subheader">The quality of your fixtures matters. When redesigning your home, you are making an investment that will improve the quality of your life for many years to come. Look below for the products we use to see some of your options.</p>

    <ul class="small-block-grid-3 medium-block-grid-6 large-block-grid-6">
        <li><%=link_to image_tag("brands/brand1.png"), "http://www.lacava.com", :target => "_blank"%></li>
        <li><%=link_to image_tag("brands/brand2.png"), "http://www.gessi.com", :target => "_blank"%></li>
        <li><%=link_to image_tag("brands/brand3.png"), "http://www.kohler.com", :target => "_blank"%></li>
        <li><%=link_to image_tag("brands/brand4.png"), "https://pro.hansgrohe-int.com/18863.htm", :target => "_blank"%></li>
       <li><%=link_to image_tag("brands/brand5.png"), "http://www.bainultra.com/", :target => "_blank"%></li>
       <li><%=link_to image_tag("brands/brand6.png"), "http://www.hansgrohe-usa.com", :target => "_blank"%></li>
    </ul>

  </div>
<div>

<hr class="style-two">

app/views/static_pages/contact.html.erb
<div class="row">
  <div class="medium-6 columns">
    <h3>CALL FOR A CONSULTATION</h3>
    <h4>References available upon request.</h4>
    <p>If you have any questions about the services we provide please call or email us.  Feel free to use the form on this page to send us an email.  Don't forget to include your correct email and phone number so that we can contact you.  If you love your renovation and want others to know, please send us your feedback!</p>

    <div class="show-for-large-only">
      <ul class="button-group ">
            <%= render 'contacts/info' %>
      </ul>
    </div>

  <div class="hide-for-large-only">
      <ul class="stack button-group">
      <%= render 'contacts/info' %>
      </ul>
    <div class="space"></div>
  </div>
</div>

  <strong class="hide-for-small-only">
    <div class="medium-6 columns">
      <%= render "contacts/new" %>

  <% if flash %>
      <div>
        <% flash.each do |key, value| %>
          <div style="color:red">
            <%= value %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  </strong>

<hr class="style-two">

app/views/static_pages/designs.html.erb
<div class="row">
  <div class="large-12 columns">
    <h2>Design &amp; Renovation</h2>
    <p>At CM Suby, we offer a variety of services to suit your needs. Check out our gallery below to see our work!</p>
  <hr class="style-two">
  <table>
    <thead>
      <tr>
        <th width="200"><h5>Services we offer</h5></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Kitchen and Bathroom Design and Remodeling</td>
        <td>Interior Renovation</td>
        <td>Finished Basements</td>
      </tr>
      <tr>
        <td>Custom Decks</td>
        <td>Custom Shower Doors and Mirrors</td>
        <td>Interior Repair</td>
      </tr>
      <tr>
        <td>Installation of Hard Wood Flooring</td>
        <td>Demolition Removal and Disposal</td>
        <td>Cabinetry</td>
      </tr>
    </tbody>
  </table>

  <hr class="style-two">
    <ul class="tabs" data-tab>
      <li class="tab-title active"><a href="#panel1">Kitchen</a></li>
      <li class="tab-title"><a href="#panel2">Bathroom</a></li>
      <li class="tab-title"><a href="#panel3">Laundry Room</a></li>
      <li class="tab-title"><a href="#panel4">Other</a></li>
    </ul>

    <div class="tabs-content">
      <div class="content active" id="panel1">
        <%= render 'galleries/kitchen' %>
      </div>
      <div class="content" id="panel2">
        <%= render 'galleries/bathroom' %>
      </div>
      <div class="content" id="panel3">
        <%= render 'galleries/laundry' %>
      </div>
      <div class="content" id="panel4">
        <%= render 'galleries/other' %>
      </div>
    </div>
  </div>
</div>

<hr class="style-two">

app/views/static_pages/index.html.erb
<h2 class= "text-center">Home Renovations</h2>

<div class="row">
  <div class="large-12 columns">
    <div class="large-12">
      <div class="hide-for-large">
        <div id="featured" data-orbit>
          <%= render 'galleries/banner' %>
        </div>
    </div>

  <strong class = "show-for-large">
    <div class="smoothslides" id="myslideshow1">
          <%= render 'galleries/banner' %>
    </div>
  </strong>

  <hr class="style-two">

  <div class="row">
    <h1 class = "text-center">Why Work with Us</h1>
    <div class="large-4 medium-4 columns">
      <%=link_to image_tag("index_intro/main_intro_1.png"), testimonials_path%>
      <p>We have a long and growing list of happy customers. In fact, most of our customers use our services again and again for their homes. Browse our <strong><%= link_to "customer testimonials", testimonials_path %> </strong>– they speak for themselves!</p>
    </div>
    <div class="large-4 medium-4 columns">
      <%=link_to image_tag("index_intro/main_intro_2.png"), approach_path%>
        <p>We’re take pride in ensuring that every last detail of your project is perfect. We use the highest quality products and a meticulous work ethic to ensure a top of the line result. <strong><%= link_to "Click here", approach_path %></strong> to learn more about our process.</p>
    </div>
    <div class="large-4 medium-4 columns">
      <%=link_to image_tag("index_intro/main_intro_3.png"), designs_path%>
      <p>Take comfort in knowing that a professional contractor with full credentials and years of experience is taking care of your home. Check out our <strong><%= link_to "past works", designs_path %></strong>!</p>
    </div>
  </div>

  <hr class="style-two">

  <h1 class = "text-center">Before and After</h1>

  <div id='container3' div class="twentytwenty-container">
    <img alt="Sample before" src="/images/testimonial/kitchen_before.png"/>
    <img alt="Sample after" src="/images/testimonial/kitchen_after.png"/>
  </div>

  <p class="text-center">Browse some of our dramatic Before and After project pictures on the <strong><%= link_to "Testimonial Page", testimonials_path %></strong>.</p>

  <hr class="style-two">

  <div class="row">
    <div class="medium-6 columns medium-push-6">
    <img class="thumbnail" src="/images/index_intro/profile_shot.jpg">
    </div>
    <div class="medium-6 columns medium-pull-6">
    <h2>A Quality Renovation Starts with a Reliable Contractor...</h2>
    <p>At CM Suby, customer satisfaction is everything. We will work with you, alongside our design professional, from start to finish planning each detail with your approval. Once you are satisfied, we then begin ordering materials for the job and will not begin work until we have everything in our possession. We only start one project at a time so your project is always our number one priority.</p>
    </div>
  </div>

<hr class="style-two">

<div class="row">
  <div class="large-8 columns">
    <div class="panel radius">
      <div class="row">
        <div class="large-8 columns">
          <h4>Check out our Instagram!</h4>
          <!-- LightWidget WIDGET --><script src="//lightwidget.com/widgets/lightwidget.js"></script><iframe src="//lightwidget.com/widgets/63c62e24a29b5fe99cf6a4f3c3afec91.html" id="lightwidget_63c62e24a2" name="lightwidget_63c62e24a2"  scrolling="no" allowtransparency="true" class="lightwidget-widget" style="width: 100%; border: 0; overflow: hidden;"></iframe>
        </div>
      </div>
  </div>
</div>

  <strong class="hide-for-large-up"><hr class="style-two"></strong>

    <div class="large-4 columns">

    <h4>Communicate with Us!</h4>
    <div class="show-for-large-only">
      <ul class="button-group ">
        <%= render 'contacts/info' %>
      </ul>
    </div>

  <div class="hide-for-large-only">
    <div class="button-bar">
      <ul class="button-group">
      <%= render 'contacts/info' %>
      </ul>
    </div>
  </div>

</div>

<hr class="style-two">

app/views/testimonials/_amy.html.erb
<p>Morgan Suby recently renovated our master bath. He and his crew were meticulous with every detail. The crew kept the area incredibly clean and the work went off without a hitch. We highly recommend him and will look to him for any future renovations. His level of professionalism and understanding of products was second to none. It is never fun living through remodeling but Morgan and his crew made it manageable.</p>

app/views/testimonials/_damon.html.erb
   <p>It was an absolute pleasure working with Morgan and his team.  From start to end they were professional, friendly and on time.  They took our tired looking 20 year old master bathroom and turned it into a custom spa like retreat for me and my wife.  We couldn’t be happier and I would highly recommend Morgan to anyone looking for a detail oriented professional who does what he says he will.</p>

app/views/testimonials/_david.html.erb
     <p>I have used C.M.Suby ("Morgan") for two separate bathroom renovation projects and have been very pleased with both the experience and the results for a number of reasons.  First and foremost, I was extremely impressed with Morgan's concern for quality and his attention to detail.  One of the reasons that my bathrooms turned out so well is that everything was carefully and properly installed.  Others have commented favorably to me on the appearance of my bathrooms and want to know who did such nice work. </p>
     <p>I was also impressed by the courtesy, respect, and professionalism that Morgan and his crew exhibited.  Morgan always returned phone calls, showed up on time, etc.   I appreciate the fact that the work on my projects was essentially completed on consecutive days.  I would happily trust Morgan again with another renovation project!</p>